# Site settings
title: "VIP"
motto: The cool way to organize your virtual video collection
email: casapaoc@mail.gvsu.edu
description: > # this means to ignore newlines until "baseurl:"
  VIP is the cool way to organize your virtual video collection.
baseurl: "/vip-project" # the subpath of your site, e.g. /blog/
url: "http:cyril-casapao.github.io/vip-project" # the base hostname & protocol for your site
github_username:  cyril-casapao

# Build settings
markdown: kramdown
